### ISSUE TITLE
Out of bounds unexpected behavior

### ISSUE THREAD

**Issue by evangibson** [evangibson/pathfinder_game#3]
As shown below, when executing a right move to out of bounds does not add to the score. Rather the behavior is to exit the maze. The expected behavior is to add a wall error

```

Current Turn:  0
Distance to Target:  2.0
Penalty Score:  0
Score:  -2.0
[[  0   0   0   0]
 [  0  -1   0   0]
 [  0   0   0   0]
 [  0  -2   0 101]]
Move Direction: r
Traceback (most recent call last):
  File "random_maze_single_actor.py", line 118, in <module>
    main()
  File "random_maze_single_actor.py", line 91, in main
    active_game.action_request(active_game.players[next(iter(active_game.players))])
  File "C:\Users\{USER}\Documents\Python\pathfinder_game\objects\game_play.py", line 95, in action_request
    accept = self.check_move(action)
  File "C:\Users\evang\Documents\Python\pathfinder_game\objects\game_play.py", line 67, in check_move
    if self.play_map.maze[proposed_position[0], proposed_position[1]] == self.play_map.goal_value:
IndexError: index 4 is out of bounds for axis 1 with size 4

```

**Comment by evangibson** [comment]
The problem comes from a check for a game win; when the player is out-of-bounds, he/she will be ejected if the code doesn't check for a win by position. The recommended fix is to insert "try/except" to handle the index error. This should work because the score is still being adjusted for the wall penalty and appending an e101.

**Comment by evangibson** [comment]
Issue solved in today's push. Behavior is now stable.
